### ISSUE TITLE
No audio on PH and Line output

### ISSUE THREAD

**Issue by sawacs** [b-ak/audiosense-pi#1]
Hi.
My hardware: RaspberryPi 4/4GB with latest Raspbian kernel 4.19.

![DSC_5867](https://user-images.githubusercontent.com/48694194/65722213-156d6b80-e0ac-11e9-99d4-f51f172e2649.JPG)

I have two AudioSense-Pi that I have assembled myself.

![2019-09-26-214824_1920x1080_scrot](https://user-images.githubusercontent.com/48694194/65720604-975b9580-e0a8-11e9-96e5-24c13bfca73c.png)

I added all necessary entries to /boot/config.txt:
dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=on
dtoverlay=lirc-rpi
dtoverlay=audiosense-pi

My problem is that there is no audio signal on both headphone and line outputs.

Test i did:

![2019-09-26-225442_1920x1080_scrot](https://user-images.githubusercontent.com/48694194/65724444-b3fbcb80-e0b0-11e9-8a8e-471bab4ef589.png)

1: ffmpeg -i Downloads/1kHz_44100Hz_16bit_30sec.wav -af "pan=stereo|c0=c0|c1=c0" -ar 48000 -f alsa hw:1,0

![2019-09-26-225550_1920x1080_scrot](https://user-images.githubusercontent.com/48694194/65724529-e1e11000-e0b0-11e9-9388-c3436c72a3d4.png)

 No audio output! I noticed that "time" increases every two to three seconds and "speed" drops from 0.99 downwards v. fast...
It's the same for both PCBs
Perhaps something is wrong on the PCB, but all the elements were new and I tried to assemble them very carefully!
I'm sure raspbian os recognizes AudioSense-Pi correctly. I carried out the test by giving an audio signal to the LineIn input and switched "Bypass" - HPL / R Output Mixer IN1L / R
![2019-09-26-230947_1920x1080_scrot](https://user-images.githubusercontent.com/48694194/65725497-1950bc00-e0b3-11e9-93d4-5c20d4bb4b20.png)
![2019-09-26-230953_1920x1080_scrot](https://user-images.githubusercontent.com/48694194/65725500-1a81e900-e0b3-11e9-9049-15c9b644e232.png)
I heard on the headphones what was on the line input... I2C is working...
OK. 
For today I have to finish ... 

Maybe someone has an idea where is the problem ....? 
Or maybe someone already had such a problem ...?

By

**Comment by b-ak** [comment]
Can you try this command `arecord -D hw:1 -c 2 -r 48000 -f S16_LE | aplay -D hw:1` 
Connect an audio source to `J2` - `Mic-In` and check what's on your headphones

**Comment by sawacs** [comment]
Hi!
There was a problem here 
![sketch-1569844836408](https://user-images.githubusercontent.com/48694194/65877313-a46bd380-e38b-11e9-9287-bf51239966a0.png)
... I soldered two resistors R10 and R11 wrongly!
![DSC_5867](https://user-images.githubusercontent.com/48694194/65878637-db8fb400-e38e-11e9-99de-691ad16cd353.png)

Now I'm going to tests ...

**Comment by b-ak** [comment]
Great!! Any updates? Have you got it working?

**Comment by sawacs** [comment]
I apologize for the short delay in my response ... I was away for a few days.
Yes. I confirm that my tests were successful. Recording works, playback works. Now I am learning the other possibilities of TLV320 ...
Thanks for the help.
... I will try to run modules on OrangePi and NanoPi M4 after some time.

**Comment by b-ak** [comment]
Great to know that. Thank you for a detailed report, it'll help other people trying to recreate the board :)
Also, I'd request you to please drop in the updates about the experiments with OrangePi and NanoPi..
